language: node_js
node_js: stable

before_install:
- npm install -g hexo-cli
- npm install hexo --save
- npm install hexo-deployer-git --save

# S: Build Lifecycle
install:
  - npm install

before_script:
  - hexo clean 
  - git config --global user.name "r1v3rj1s"
  - git config --global user.email "djieastgo@yahoo.com"
  - sed -i "s#${GH_REF}#${GH_TOKEN}@${GH_REF}#g" _config.yml

script:
  - hexo g 
  - hexo d

# E: Build LifeCycle

branches:
  only:
    - second-institute