language: node_js
node_js: 13


before_install:
  # Basic config
  - sed -i "s#${LC_CRITIQUE_TMP_ID}#${LC_CRITIQUE_ID}#g" themes/next/_config.yml
  - sed -i "s#${LC_CRITIQUE_TMP_KEY}#${LC_CRITIQUE_KEY}#g" themes/next/_config.yml
  - sed -i "s#${LC_VISITOR_TMP_ID}#${LC_VISITOR_ID}#g" themes/next/_config.yml
  - sed -i "s#${LC_VISITOR_TMP_KEY}#${LC_VISITOR_KEY}#g" themes/next/_config.yml
  - sed -i "s#${LC_VISITOR_TMP_ID}#${LC_VISITOR_ID}#g" _config.yml
  - sed -i "s#${LC_VISITOR_TMP_KEY}#${LC_VISITOR_KEY}#g" _config.yml
  - sed -i "s#${USER_TMP_ID}#${USER_ID}#g" _config.yml
  - sed -i "s#${LC_COUNTERSECURE_TMP_TOKEN}#${LC_COUNTERSECURE_TOKEN}#g" _config.yml
  - git config --global user.name "r1v3rj1s"
  - git config --global user.email "djieastgo@yahoo.com"
  - sed -i "s#${GH_REF}#${GH_TOKEN}@${GH_REF}#g" _config.yml

  # Restore last modified time
  - "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"

  # Deploy history
  - git clone --branch=master --single-branch https://${GH_REF}.git .deploy_git


install:
  - npm install babel-runtime@6
  - npm install -g hexo-cli
  - npm install hexo --save
  - npm install hexo-deployer-git --save
  - npm install hexo-leancloud-counter-security --save
  - npm install


before_script:
  - hexo clean 


script:
  - hexo g 
  - hexo d


git:
  depth: false
branches:
  only:
    - second-institute    
env:
  global:
    - secure: "DWlIMfki1nPPStO2CxnRiKoU7heO28i7t6tPVTAoLHtVCpprrflt2UVDAj4s8uZJqlggf2I2P7Gmjctam9d/eTaFS6WiH5zH98pmAIc8NAl5DXOsgx1N8gLw92235VN33JUlNJK3RZ6GeMdZ/ougb4eazTpY0r4Wm55K9fJqo+yOPOvuinGainprPgMaH+4oLpmCiplA7wjb6yVAh/PKZhdkq5KS9cKXG51FhUBix0nleODbyZLtOO2WbtMFcxBzhpXQ9TzcUSmSCuxleatVFY1C8IrzirIeECG+Ky2gs0pAWAvgfTsihub2mr7IqrXiEqyaFbbcGi2DzUuzaV9H6FGy+V+JLIcLWhpB/6Ow5K56TJXeaYXRvot8ZqpuZc7ixQhvLk30ACbW/OJv+lTZD/4KyQNpw72n+5V2pMIxScXfgArCQO9r/YtS6WHojupuEZt1SkCHeuPfNAtaIN8lEqBsI90E3S7aZBt+wjOW4dulVJO8IJmEPix4y0WjqU9kGVKvM/wnomGfxqV2k72YF8B2RYlatQEHqnQwptP/PXP2RfeXNWkvzYevHZu+Ar9J+pkDIcUt/m/Pi9Ku8eKOu2GMmmWolxj9MUomaDoxdQvWY8uNpQG74MAs9mIm1LP1hqtQOZkNRzAI+f4qwZMyg9JZYVoQDbd9pvmXGJXlyIo="
    - secure: "W+ci34H+XTyJsRAUdHDS8HEedvcyVCx3Tv9oEnceO8yFUzomrpBUks+D2e31/JrL772IRz+mFV/06m+7cqOOLuX38zdPHcGhYXbI1mRsayXToquYKhC2CQDm9yIfxzQFAwXAAL8MXxmXfk5ZXeZRw/a3m8p96Azvjt/v8EhHYi69woPILVHjBmZ+/pv9bm4JfqV0albU6yj4fc3mnUBAVToM6ss07ZoS4x6ktMw9F93GeLmpLjwBzht5RsO4xKZ6YEoegoCYUkTkRCd1IdzTTMJwcw9BCdM+gHkoEs21VdRB62CXxlvWYWA/WH4Ek0WXJbtkdpwYpxtEl4/nHXWX1i6Nz6ABBAcGL3Ekg+CQzgwMO62U/7O60pnvNEqBwwgZYuXkqHlGe37e6766iFMbvOzilWf/MUzgKoGzgkZRZZ66pgBqhOxqOzLMJj/zlk8EPQ1VAqNaGDcCXmCm2ZO2bCSrb3rZz5GcdTwiRjZb39j98BLRJNSxTxu2Thu3izcZfyPFw6Jvkc7xjjI5vJ0gjd/zorq/lXGO2AvFfwlK7wMN8VXHdsieIM4sv3jMYr9o0c6g1gO7AtW2Vkix9RRRXhC2TAXNVxiSYfcDCTa4RxFwjqjbPSET+beMJYusRo+VVZovOt4FwR5jrKRNBXEMb7NjphbUHbXinOL//UHKNr0="
    - secure: "oGIc/SDjpiY2CLoM6dzHKFUbxky3z3wCQLPHKtW0jFhNDNhwE9dACYD2Rgr6cj3sXTWmHeR3RJlxqXvLukQseMoIwMuciLeEnDJpHYk27+EuzU3F8LwCn3T5dhhqAhDY8Wi+LsyJ/nyzKJYxhpljphPVFILwGYH9RS3BJWMxccinVQbr4yDsI1ENIZCs9zagjuJQc9x8oSzreLAU63GZEy9yr91hBn4VC6gVb992bbHb+/0bmEXVlh4S8w9+iOML/YG2GmOS+aXJnaeG7BveOHWC+o+NXc6zuFG/nFvXQvy3tquCMINs9GwSMTJikkY9XJDTC4UilKXlpEYqow3wUucCssgh9EkvziX1xmgSUdC+fQVAHWuIBM0F+reKTgr0ALnUMQ6kmOILxokSK2xKe0f+GwQexYdnyPEkBaB8PEZzveSP0ZKi82p08UMiMs9E9OIdxwdd8unzo+uNYu6FepsSJ+R8T4f6KYQrC46+8/rNRkcOvyXwwSrd/wotHbyTMSNTdJJ3mJqm5VLUaimPU7oQtKnKJWqNTwuxWtFBEnd38qhJYRi4/6+V3rXZvoVS/oiqY5ZE7QE2q+3vmYkmt5M8RfiaR6TMECZDBTSNPpNBW5oArajvhmkZe5i7QcEOdEp6wKB0QvJCDAmcgWA1kw51XK6aj87nwk3Ezkft1p4="
    - secure: "kjwOVKKhmJ/qS/RxqoZtv+khmvBBvI/fZd96gFVJyJgXQTUlwZrhyHOcEyA5/9V5MIKjkm7k064Leo88VFJzZTkyau1ilWR029l/7NH2zBczHiWogJfJL5HuRYG6OhMZRxwaFqnfH+T1B6m9cFT3IFJ10wG4xHEsNMpVHtS6IJTztJYUtuMAoXxpSxbO+En+qMFAHlReRVJbMR9fXJWZAJ/oRwvcbSYijeC31ESHwGExacOFaGNJTsbxdxVf7M5YIJo1yWG7QiVTskIkQDJxewN0h+7gclXBj4UlT223WmMrSRFaSt1+HbF4dnWdaDZbQ9pCdYwHGXtxlGC4W9j8yeKVX8C5BJSiTFXM1zuqYR83Fr4dFOzQCzX8QyiTfrzA08WMf3Tmk3x9UzhFqyPUDoJk7HctBjcJtkc2ezuia2hThBrndN3++1VMR8hGLmRnal+sGGu3szOL4WnD3zrwOXa6pItUUx++jSGaMZIJPzXuS2pcUEUwaujvH8wagOZghjOnxYGNsE7s6b7b7IWElmJb7PcMAtkBJGb3S03RqmEatyLy0CssEJbUV5PddvD5Qlc8BIApHFaUQp2tDvG4YknJrqK7jK6DlQ34Lzf6X4vd+BhiXaNXbc4ctaqrKtRbdQr/ArNn7bqJR2LDghORQvuPpnKy0ZsVEScQTtdD+Dw="
    #- secure: "ViIl+69p8oemCqqvHr8Q1KsUVMLl8LMt926dreUqIQTET7uAQhmaUeIAgaM9WNRek8ZYBZpe4e5Rb0lZ5HQi+SS5j8ZyxxuKMcTyI2ydTNPArDXG20t3lwIEtKN0/y5gz0eE1bOZFM0VfRZBBBaMBFwh6sasbVAXwUXRq0IJ0Q33F4ZLDtIokFjTyKh9pq23FV5mDQsZM+r/CExSHtOgm8y8phgUYxBbNSw2vGnApwovnMUWIzp5hCLnzIC0KvtpJQd+bnO2K9Ctp7gaqL4+an45IM20RninBQo3BxKhxKUOvnXHkEKVL1+QXMBTqG4SaI62Y3k8+aS79QFIh451vBFTEz+oJH3DgaLmnLfOaIvsFDeW9sKIb9UTG5aUWsk9CxTOabfUT7rTh2Z6RyiiArs7nuaC2+BCI0feEiV5U0Z4mlmjowFTJlW9kfbCx/42nMswOWjCUDETj1ZYfCzZmopfyqWnnjd4mbRznyUy2OgGR23NgWb5U8vY/YnLAPLnf60/ejDDh3S0kHDssh6aAMJgKbIIHL791fKqyw2h/VW2gRNvMPNeEZE9WNmPK64dfCO/qH8iOH7fx0VMRDXc0yAFTNIsQInGoJi+jfqKI7H18fUD4/vedKIcGv+C8XNTEq4q3i/GhLGWbstFspd+8jyk35nTMkarRI5CeXuPp64="
    - secure: "n+uJ/fkHgs9cDEvof9Oj3R71dimPBp4OPxy29Hg13/Hh9fsDWNI9amH//8MmNmkDjRMOghUd6Hr3Fj+TH4DE4ocEPbRxwH0fu21W01LylwRrRa/aA/pySolMUUDIue0Xqn9xZ5iR1480psqeta7TQgahViF78O4nW31C+MX9qufXNaHpfvm+Dys6BC2HXJt2tDqAr16jxJFWIGU702bwtAPg6u95Bd5CIHJ4T2uuCpWqKu7TySTKl1LT2wxYTAbBtF0ZlF28j7BHPZFgM9U/n1EjM7XEcwhPJIfe1PoorlLaF3d7qXgK7yDq6kg+IEeJdd0BdLQnmYXSeCyNdF+TUVdLdz2LjyHt7l3bVsQEVa3WmchUghWr0Z45kd2btHA/NkKeTWjro6ZdUxY/bQSnawLcwoK4+/hZOPk6FcKoPBYs9zqVv7DIJ46h0zUmL+I0mPctxOuhZLQqRx8AUShsMSc2qRh7/hg2hGdn/424TFZPX6lxGhaOztaA5iOSmagHO5C5OHNfcd5FUxUOXAo3liGn3hgkCvMAQLtUn5R2/oAkK8S3dmthlBdMaSy2bPH3rwlgCfjrYa8LRpYfocdeV1bavqEk585el+dhGr3+9NWYQad/yEB/Nv3sGYgKqwXCnRn1+suQ5TAYnORxgRbcBXTqzKNZabwFbCdoN9CtxQc="
    - secure: "ABs30p0NqV62MTB5X2dn55/LAr66AIizvowJCLQn3jAl4uph8gtZt50lm85m9RgfRNg+c/4OFbrHwo2ymBHATgIZUlI13Il4Z4yACINA7fdmOBjqqss9qeFioGr2Xj2/a61y0H9lkDSn52E8v3IEpXmgGr6QTA23qmK9Y8lT9zuQ5Z+Ecccw7iXAgiFbdlh1Rf3LaNLInH3bR1gPb430pPhoeiy05i1NjtxyYtVlxq4Q7ITpE/pn1oR8YZPoQGldnXnNTM4gKx/LiOocKOSFjg6XSHN+prKVMujErD9H2VwlogGd42mabkVLrXLeNKtTANAmo3YT9a4JMP8ESR27/NoZqQLj8u83HmMm4bEHoiJA6PuJjhOvKTXx82Q9mxMiTbBOnjPJL/Ha4BHwQB/Oy368cPAeQ2IjklYkg6wyrYh30fI9JMd9FGoXufDDooyLTgR6GWCb2XRlDqzfnm+AJo8Bjwkg5NofxLE/mJupX9ZXm2/JIakcvuWIYHqUcS6liofzH2QF5z2M0N/MQVQ0upXuzj9y0h8LTnsf9Za3yiLGPswLZkShYbXrIqQ+siZzsnVi/sx543J95yEA5WGA5OOq20Le9MycNIJ6Vly5srbbztC/Cqvj07W4Tko3qrTgPsEobeY9wITvzbPuyQxk4hREe0uNjQePZEhSzFwTfRI="
    - secure: "QVYPwou+2vIt2NsegecO7MBzvuhBeyO66MToK2EhAEP2y3bQCrtHprO7myaTiN984ykZE2WdIm6Gjyb+m9vTa385XtkgYBFPeNuh0e2N/Zk6fhaQD5mYVIzP95xzIwa7YrppY7BYWCagcE69NDfoMMy7WjTRk59cP0UeS5uK47pB0pyvegJQ1h5OTCKPTrnJYfxuuwjPsdnavXa3M8zChykc8cULbhbM07LVxyVMV5v6tyYMz++Xhyl11kT9cwHYELnOt7hXLDBxxy2/IwhAJfPg3sUJZl83cOSunvqSc1ZkSBvj8dAcjIRJCaBOSzSpl3RGEJIzJOzDir3CwBSJyU1uMTlVVqnXWavcyya2emjWVJrHqpxS+fioQou1BRuv+bbLnkBfEN1rKelmUkx0BKnd349L1DqOXCCoMR7c8HpQOKSPWxk8faxH32HI4kToE74R2CeC35Lst9gbUQJ8rr9BvVj6lHhu1ku6H5KW6W01+kIxCMwZCOu0tOKo2Cl+T8JAA+Q3sXhYjuSeX8qhrFOIg+IunPapY5e3e68On8vQj6gxacGZF5ot4qrrblHBJsqP4GJQtHSAXEFE5Pd3ZqdhGhSQ0hpT2vSTNBT1nE1mHziPp0xk5H7e4JkFton66DVw2JxljpchRFBSwJJxzkl/EZRP6n6FOibuNXdwYFk="



